iran_provinces = [
    {"name": "Tehran", "url": "https://divar.ir/s/tehran-province"},
    {"name": "Alborz", "url": "https://divar.ir/s/alborz-province"},
    {"name": "Isfahan", "url": "https://divar.ir/s/isfahan-province"},
    {"name": "East Azerbaijan", "url": "https://divar.ir/s/azarbaijan-east-province"},
    {"name": "West Azerbaijan", "url": "https://divar.ir/s/azerbaijan-west-province"},
    {"name": "Razavi Khorasan", "url": "https://divar.ir/s/khorasan-razavi-province"},
    {"name": "South Khorasan", "url": "https://divar.ir/s/khorasan-south-province"},
    {"name": "North Khorasan", "url": "https://divar.ir/s/khorasan-north-province"},
    {"name": "Fars", "url": "https://divar.ir/s/fars-province"},
    {"name": "Gilan", "url": "https://divar.ir/s/gilan-province"},
    {"name": "Mazandaran", "url": "https://divar.ir/s/mazandaran-province"},
    {"name": "Hormozgan", "url": "https://divar.ir/s/hormozgan-province"},
    {"name": "Qom", "url": "https://divar.ir/s/qom-province"},
    {"name": "Qazvin", "url": "https://divar.ir/s/qazvin-province"},
    {"name": "Kurdistan", "url": "https://divar.ir/s/kurdistan-province"},
    {"name": "Kerman", "url": "https://divar.ir/s/kerman-province"},
    {"name": "Kermanshah", "url": "https://divar.ir/s/kermanshah-province"},
    {"name": "Yazd", "url": "https://divar.ir/s/yazd-province"},
    {"name": "Lorestan", "url": "https://divar.ir/s/lorestan-province"},
    {"name": "Hamedan", "url": "https://divar.ir/s/hamadan-province"},
    {"name": "Zanjan", "url": "https://divar.ir/s/zanjan-province"},
    {"name": "Bushehr", "url": "https://divar.ir/s/bushehr-province"},
    {"name": "Golestan", "url": "https://divar.ir/s/golestan-province"},
    {
        "name": "Chaharmahal and Bakhtiari",
        "url": "https://divar.ir/s/chahar-mahaal-and-bakhtiari-province",
    },
    {"name": "Ilam", "url": "https://divar.ir/s/ilam-province"},
    {
        "name": "Kohgiluyeh and Boyer-Ahmad",
        "url": "https://divar.ir/s/kohgiluyeh-and-boyer-ahmad-province",
    },
    {
        "name": "Sistan and Baluchestan",
        "url": "https://divar.ir/s/sistan-and-baluchestan-province",
    },
    {"name": "Ardabil", "url": "https://divar.ir/s/ardabil-province"},
    {"name": "Markazi", "url": "https://divar.ir/s/markazi-province"},
    {"name": "Khuzestan", "url": "https://divar.ir/s/khuzestan-province"},
]
